#
#   Copyright (c) 2017-2018 Joy Diamond.  All rights reserved.
#
@module('CoreParser.Core')
def module():
    transport('Capital.Cache2',                     'create_cache')
    transport('Capital.Cache2',                     'produce_conjure_unique_dual')
    transport('Capital.Cache2',                     'produce_conjure_unique_triple')
    transport('Capital.Cache2',                     'produce_conjure_unique_triple__312')
    transport('Capital.Cache',                      'produce_conjure_dual')
    transport('Capital.Cache',                      'produce_conjure_dual__21')
    transport('Capital.Cache',                      'produce_conjure_triple')
    transport('Capital.Cadence',                    'cadence_constructing')
    transport('Capital.Cadence',                    'cadence_entered')
    transport('Capital.Cadence',                    'cadence_exception')
    transport('Capital.Cadence',                    'cadence_exited')
    transport('Capital.Cadence',                    'cadence_initialized')
    transport('Capital.Cadence',                    'cadence_reuse')
    transport('Capital.DelayedFileOutput',          'create_DelayedFileOutput')
    transport('Capital.Exception',                  'Exception')
    transport('Capital.Global',                     'capital_global')
    transport('Capital.Method',                     'return_self')
    transport('Capital.Path',                       'path_basename')
    transport('Capital.SimpleStringIO',             'create_SimpleStringOutput')
    transport('Capital.StringOutput',               'create_StringOutput')
    transport('Capital.StringOutput',               'StringOutput')
    transport('Capital.System',                     'caller_frame_1')
    transport('Capital.System',                     'slice_all')
